
services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "80:5678"

    environment:
      TZ: Asia/Ho_Chi_Minh
      GENERIC_TIMEZONE: Asia/Ho_Chi_Minh

      # URL PUBLIC của n8n (quan trọng khi chạy reverse proxy)
      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http

      # FIX lỗi secure cookie
      N8N_SECURE_COOKIE: false

      # Đặt thư mục để lưu dữ liệu workflow
      N8N_USER_FOLDER: /home/node/.n8n

      # Tăng giới hạn tải file
      N8N_PAYLOAD_SIZE_MAX: 50

    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
